/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Tab,
} from './components/tabs/utils/tab';


export namespace Components {

  interface TqList {
    'items': Tab[];
    'selectedIndex': number;
  }
  interface TqListAttributes extends StencilHTMLAttributes {
    'items'?: Tab[];
    'selectedIndex'?: number;
  }

  interface TqSearch {
    'suggest': string;
  }
  interface TqSearchAttributes extends StencilHTMLAttributes {
    'onOnSearch'?: (event: CustomEvent) => void;
    'suggest'?: string;
  }

  interface TqTabs {
    'historySinceDays': number;
    'maxHistoryItmes': number;
    'minInputLength': number;
  }
  interface TqTabsAttributes extends StencilHTMLAttributes {
    'historySinceDays'?: number;
    'maxHistoryItmes'?: number;
    'minInputLength'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TqList': Components.TqList;
    'TqSearch': Components.TqSearch;
    'TqTabs': Components.TqTabs;
  }

  interface StencilIntrinsicElements {
    'tq-list': Components.TqListAttributes;
    'tq-search': Components.TqSearchAttributes;
    'tq-tabs': Components.TqTabsAttributes;
  }


  interface HTMLTqListElement extends Components.TqList, HTMLStencilElement {}
  var HTMLTqListElement: {
    prototype: HTMLTqListElement;
    new (): HTMLTqListElement;
  };

  interface HTMLTqSearchElement extends Components.TqSearch, HTMLStencilElement {}
  var HTMLTqSearchElement: {
    prototype: HTMLTqSearchElement;
    new (): HTMLTqSearchElement;
  };

  interface HTMLTqTabsElement extends Components.TqTabs, HTMLStencilElement {}
  var HTMLTqTabsElement: {
    prototype: HTMLTqTabsElement;
    new (): HTMLTqTabsElement;
  };

  interface HTMLElementTagNameMap {
    'tq-list': HTMLTqListElement
    'tq-search': HTMLTqSearchElement
    'tq-tabs': HTMLTqTabsElement
  }

  interface ElementTagNameMap {
    'tq-list': HTMLTqListElement;
    'tq-search': HTMLTqSearchElement;
    'tq-tabs': HTMLTqTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
