/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { List as TqList } from './components/list/list';

interface HTMLTqListElement extends TqList, HTMLElement {
}
declare var HTMLTqListElement: {
  prototype: HTMLTqListElement;
  new (): HTMLTqListElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "tq-list": HTMLTqListElement;
  }
  interface ElementTagNameMap {
      "tq-list": HTMLTqListElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "tq-list": JSXElements.TqListAttributes;
      }
  }
  namespace JSXElements {
      export interface TqListAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          selectedIndex?: number,
          items?: any
      }
  }
}

import { Search as TqSearch } from './components/search/search';

interface HTMLTqSearchElement extends TqSearch, HTMLElement {
}
declare var HTMLTqSearchElement: {
  prototype: HTMLTqSearchElement;
  new (): HTMLTqSearchElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "tq-search": HTMLTqSearchElement;
  }
  interface ElementTagNameMap {
      "tq-search": HTMLTqSearchElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "tq-search": JSXElements.TqSearchAttributes;
      }
  }
  namespace JSXElements {
      export interface TqSearchAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          suggest?: string
      }
  }
}

import { Tabs as TqTabs } from './components/tabs/tabs';

interface HTMLTqTabsElement extends TqTabs, HTMLElement {
}
declare var HTMLTqTabsElement: {
  prototype: HTMLTqTabsElement;
  new (): HTMLTqTabsElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "tq-tabs": HTMLTqTabsElement;
  }
  interface ElementTagNameMap {
      "tq-tabs": HTMLTqTabsElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "tq-tabs": JSXElements.TqTabsAttributes;
      }
  }
  namespace JSXElements {
      export interface TqTabsAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          maxHistoryItmes?: number,
          minInputLength?: number,
          historySinceDays?: number
      }
  }
}

